server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: player-stats-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/players/**

        - id: stats-aggregation-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/aggregate/**
