spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nbastats
    username: your_db_user
    password: your_db_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    # password: your_redis_password (uncomment if needed)

  jackson:
    serialization:
      INDENT_OUTPUT: true

  jpa:
    hibernate:
      ddl-auto: none  # or update / validate
    show-sql: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.data.redis.core.RedisTemplate: DEBUG
