spring:
  application:
    name: flusher-service

  datasource:
    url: jdbc:postgresql://localhost:5432/statsdb
    username: statsuser
    password: statspassword
    driver-class-name: org.postgresql.Driver

  redis:
    host: redis
    port: 6379

logging:
  level:
    root: INFO
    com.stats.flusher: DEBUG

scheduling:
  enabled: true
